config/routes.rb
Takeone::Application.routes.draw do
  resources :holidays, :except => :index

  resources :requests, :except => :index

  resources :shifts


  
  root :to => "splash#index"

  match "/manager" => "shifts#manager"


  match "/shifts/shift_taken/:id" => "shifts#shift_taken"

end

app/models/manager.rb
class Manager < ActiveRecord::Base
  has_many :holidays, :dependent => :destroy

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :userName, :god_mode, :reports_only, :firstName, :lastName
end

app/models/shift.rb
class Shift < ActiveRecord::Base
  validates :firstName, :lastName, :email, :presence => true
  validates_format_of :email, :with => /apple\.com/, :message => "You must use your Apple Email"
  validates_format_of :takingEmail, :with => /apple\.com/, :allow_blank => true,  :message => "You must use your Apple Email"

  #  errors.add_to_base "For Taker\'s Email You must use your Apple Email" if !takingemail.blank?
  #  errors.add_to_base "For Giver\'s Email You must use your Apple Email" if !email.blank?
  #end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery


#def authenticate
#  authenticate_or_request_with_http_basic "Notice: Unauthoized access of this site is prohibited. By proceeding form this point, you agree to comply with all Terms & Conditions applying to the use of this site. You will be held responsible for the appropriate use of the ID and password used to access this site, as well as all information accessed on this site. ----------------------------------------- Accessing this site during non-work hours should be for the limited purpose of viewing and checking your work schedule. Any other use of this site must be completed during manger approved and scheduled work time." do |user_name, password|
#    user_name == USER_NAME && password == PASSWORD
#  end
#end

end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  # GET /shifts
  # GET /shifts.xml
  def shift_taken
    @css =  File.read(File.join(Rails.root, 'public', 'stylesheets', 'notifier.css'))
     @shift = Shift.find(params[:id])
    respond_to do |format|
      format.html
      format.html {render :html => @shift}
    end
  end 
  def index
    @title = "Shift Switch"
    @shifts = Shift.find(:all, :conditions => {:date => Date.today - 2...Date.today + 65, :takingEmail => nil}, :order => "date DESC")
    @shiftscovered = Shift.find(:all, :conditions => {:date => Date.today - 2...Date.today + 65}, :order => "date DESC", :limit => 30)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @shifts }
      format.html { render :html => @shifts }
    end
  end

  # Just a list of all shifts for mangers to see.
  def manager
    @title = "Manager View of Shifts"
    @shifts = Shift.all(:conditions => {:takingEmail => nil}, :order => "date DESC")
    @shiftscovered = Shift.find(:all , :order => "date DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @shifts }
      format.html { render :html => @shifts }
    end
  end

  # GET /shifts/1
  # GET /shifts/1.xml
  def show
    @title = "Shift Switch"
    @shift = Shift.find(params[:id])
    @shift.endtime 
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @shift }
    end
  end

  # GET /shifts/new
  # GET /shifts/new.xml
  def new
    @title = "Posting New Shift"
    @shift = Shift.new
    @shift.date ||= Date.today.strftime('%a %b %d, %Y')
    @shift.starttime ||= Time.now
    @shift.endtime ||= Time.now+5.hour

    respond_to do |format|
        format.html # new.html.erb
        format.xml  { render :xml => @shift }
    end
  end

  # GET /shifts/1/edit
  def edit
    @title = "Shift Switch"
    @shift = Shift.find(params[:id])
  end

  # POST /shifts
  # POST /shifts.xml
  def create
    @shift = Shift.new(params[:shift])

    respond_to do |format|
      if @shift.save
        format.html { redirect_to(shifts_path, :notice => 'Shift was successfully created.') }
        format.xml  { render :xml => @shift, :status => :created, :location => @shift }

      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @shift.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /shifts/1
  # PUT /shifts/1.xml
  def update
    @shift = Shift.find(params[:id])

    respond_to do |format|
      if @shift.update_attributes(params[:shift]) && @shift.takingFirstName != "" && @shift.takingEmail != ""
        #Tell the ShiftMailer to send a Email if someone enters name and email for taking shift
        ShiftMailer.shift_taken(@shift).deliver

        format.html { redirect_to(@shift, :notice => 'Shift was successfully Taken!!') }
        format.xml  { head :ok }

      elsif @shift.update_attributes(params[:shift])
        format.html { redirect_to(@shift, :notice => 'Shift was successfully Updated.') }
        format.xml  { head :ok }

      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @shift.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /shifts/1
  # DELETE /shifts/1.xml
  def destroy
    @shift = Shift.find(params[:id])
      if @shift.destroy
        DestroyMailer.shift_destroy(@shift).deliver
      end
    @shift.destroy

    respond_to do |format|
      format.html { redirect_to(shifts_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  # GET /requests
  # GET /requests.xml
  #before_filter :authenticate_employee!

  def index
    @title = "Retail"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)  
    title ||= column.titleize  
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"  
    link_to title, :sort => column, :direction => direction  
  end
  
  
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/views/layouts/application.haml
%html
  %head
    %title
      = @title
    = stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css"
    = javascript_include_tag :defaults, "nested_form"
    = include_javascripts :workspace 
    = csrf_meta_tag 
    /= formtastic_stylesheet_link_tag 
    = include_stylesheets :common, :workspace, :media => 'all'
    = display_meta_tags :noindex => true, :noindex => 'googlebot', :nofollow => true, :nofollow => 'googlebot' 

  %body
    .container.span-24
      - if notice
        %p.notice
          = notice
      - elsif alert
        %p.alert
          = alert

      %div#header.span-24.last
        %h1.span-6.last
          NMA Schedule Team
        %h2.last
          =@title
      %div#sidebar.span-6.last
        = link_to image_tag('home.png') + "Home", root_path
        = link_to image_tag('switch.png') + "Shift Switch", shifts_path

      %div#main.span-19
        =yield

app/views/shifts/_edit.html.haml
= semantic_form_for @shift do |f|
  -if @shift.errors.any?
    #error_explanation
      %h2= "#{pluralize(@shift.errors.count, "error")} prohibited this holiday from being saved:"
      - @shift.errors.full_messages.each do |msg|
        %b= msg
  %h3.clear
    #{@shift.firstName} #{@shift.lastName}'s Shift
  %ul.span-22
    %li
      Email:
      = @shift.email
    %li
      Shift Type:
      = @shift.shiftType
    %li
      Shift Date:
      = @shift.date.strftime('%a, %B %d, %Y')
    %li
      Shift Hours:
      #{@shift.starttime.strftime('%I:%M %p')} - #{@shift.endtime.strftime('%I:%M %p')}
  %h3.clear Taker's Information
  %ul.span-22
    %li
      = f.text_field :takingFirstName, :class => "title", :placeholder => "First Name"
    %li
      = f.text_field :takingLastName, :class => "title", :placeholder => "Last Name"
    %li
      = f.text_field :takingEmail, :class => "title", :placeholder => "Work Email"

  .span-22.clear
    - if params[:action] == 'new'
      = f.submit "Post a Shift", :confirm => "Double check is the shift information correct?", :class => 'button white span-24'
    - else
      = f.submit "Take Shift", :confirm => "Are you sure you want to take this shift?", :class => 'button white span-24'

app/views/shifts/_form.html.haml
= semantic_form_for @shift do |f|
  -if @shift.errors.any?
    #error_explanation
      %h2= "#{pluralize(@shift.errors.count, "error")} prohibited this holiday from being saved:"
      - @shift.errors.full_messages.each do |msg|
        %b= msg
  %h3.clear Contact Information:
  %ul.span-22
    %li
      = f.text_field :firstName, :class => "title", :placeholder =>'Giver\'s First Name:'
    %li
      = f.text_field :lastName, :class => "title", :placeholder =>'Giver\'s Last Name:'
    %li
      = f.text_field :email, :class => "title", :placeholder =>'Giver\'s Email'
  %h3.clear Shift Information:
  %ul.span-22
    %li
      = f.text_field :shiftType, :class => "title", :placeholder =>'Type of Shift (FRS, Moblie, Red Zone, etc.)'
    %li
      = f.text_field :date, :class => "title"
    %li.time
      #{f.time_select :starttime, :class => "title", :twelve_hour => true,  :minute_step => 15}
    %li.time
      #{f.time_select :endtime, :class => "title", :twelve_hour => true, :minute_step => 15}
  .clear.span-22
    - if params[:action] == 'new'
      = f.submit "Post a Shift", :confirm => "Double check is the shift information correct?", :class => 'button white span-23'
    - else
      = f.submit "Take Shift", :confirm => "Are you sure you want to take this shift?", :class => 'button white span-23'

app/views/shifts/edit.html.haml
//%hr.space
//%h3.centered Looking at #{@shift.firstName} #{@shift.lastName} on #{@shift.date.strftime('%a, %B %d, %Y')} at #{@shift.starttime.strftime('%I:%M %p')} - #{@shift.endtime.strftime('%I:%M %p')}
%p.span-22.clear
  = link_to 'all shifts', shifts_path, :id => 'back'
= render 'edit'

app/views/shifts/index.html.haml
%p.span-22= link_to 'Give a New Shift', new_shift_path, :class => "button white"
%h3.clear Open Shifts
%br
%table.span-22
  %thead
    %tr.span-24
      %th.evens Name
      %th.evens Shift Type
      %th.evens Date
      %th.evens Time
      %th.evens Taker's Name
      %th.evens

 
  - @shifts.each do |f|
    %tr.span-24
      %td.evens #{f.firstName} #{f.lastName}
      %td.evens= f.shiftType
      %td.evens= f.date.strftime('%a, %b %d, %Y')
      %td.evens #{f.starttime.strftime('%I:%M %p')} - #{f.endtime.strftime('%I:%M %p')}
      %td.evens #{f.takingFirstName} #{f.takingLastName}
      %td.action.evens
        = link_to 'take', edit_shift_path(f), :class => 'button white'
%h3.clear Taken Shifts
%br
%table.span-22
  %thead
    %tr.span-24
      %th.evens Name
      %th.evens Shift Type
      %th.evens Date
      %th.evens Time
      %th.evens Taker's Name
      %th.evens
    - @shiftscovered.each do |f|
      - if !f.takingEmail.nil?
        %tr.span-24
          %td.evens #{f.firstName} #{f.lastName}
          %td.evens= f.shiftType
          %td.evens= f.date.strftime('%a, %b %d, %Y')
          %td.evens #{f.starttime.strftime('%I:%M %p')} - #{f.endtime.strftime('%I:%M %p')}
          %td.evens #{f.takingFirstName} #{f.takingLastName}
          %td.action.evens
            = link_to 'view', shift_path(f), :class => 'button white'

app/views/shifts/manager.html.haml
%div.span-22
  %p
    This page is only to see the record of the shifts that have been taken. You should go back to the home page if you need to give or take a shift.
  %h2
    The Shift Switch App has now switched #{Shift.count} shifts!!


%h3.clear Taken Shifts
%br
%table.span-22
  %thead
    %tr.span-24
      %th.evens Name
      %th.evens Shift Type
      %th.evens Date
      %th.evens Time
      %th.evens Taker's Name
      %th.evens
    - @shiftscovered.each do |f|
      - if !f.takingEmail.nil?
        %tr.span-24
          %td.evens #{f.firstName} #{f.lastName}
          %td.evens= f.shiftType
          %td.evens= f.date.strftime('%a, %b %d, %Y')
          %td.evens #{f.starttime.strftime('%I:%M %p')} - #{f.endtime.strftime('%I:%M %p')}
          %td.evens #{f.takingFirstName} #{f.takingLastName}
          %td.action.evens
            = link_to 'view', shift_path(f), :class => 'button white'
            = link_to 'remove', shift_path(f), :confirm => "Are you sure", :method => :delete, :class => 'button white'
%h3.clear Open Shifts
%br
%table.span-22
  %thead
    %tr.span-24
      %th.evens Name
      %th.evens Shift Type
      %th.evens Date
      %th.evens Time
      %th.evens Taker's Name
      %th.evens

 
  - @shifts.each do |f|
    %tr.span-24
      %td.evens #{f.firstName} #{f.lastName}
      %td.evens= f.shiftType
      %td.evens= f.date.strftime('%a, %b %d, %Y')
      %td.evens #{f.starttime.strftime('%I:%M %p')} - #{f.endtime.strftime('%I:%M %p')}
      %td.evens #{f.takingFirstName} #{f.takingLastName}
      %td.action.evens
        = link_to 'take', edit_shift_path(f), :class => 'button white'
        = link_to 'remove', shift_path(f), :confirm => "Are you sure", :method => :delete, :class => 'button white'

app/views/shifts/new.html.haml
//%p.span-4.push-11= link_to 'back', shifts_path, :class => 'button'
= render 'form'

app/views/shifts/shift_taken.haml
%html
  %head
    %meta{'http-equiv' => 'Content-Type', :content => "text/html; charset=utf-8"}
    %style{'type' => 'text/css'}
      = @css
    
  %body
    %table{:width => '640px', :style => 'border: 1px solid #CCC; border-radius: 20px; padding: 10px; border-collapse: separate;'} 
      %tr
        %td{:colspan => 3}
          = image_tag('PeopleTeamLogo.png')
      %tr
        %td{:width => '43px'}
        %td{:width => '480px'}
          %h2 Give One, Take One has just completed a shift switch
          %p 
            %strong #{@shift.takingFirstName} #{@shift.takingLastName} 
            just took 
            %strong #{@shift.firstName} #{@shift.lastName} 
            shift for
            %strong #{@shift.shiftType} 
            %br/ 
            on #{@shift.date.strftime('%a, %B %d, %Y')} at #{@shift.starttime.strftime('%I:%M %p')} - #{@shift.endtime.strftime('%I:%M %p')}
          %p
            An Email has already been sent to:
            %ul
              %li NMA Schedule - nma_schedule@apple.com
              %li #{@shift.takingFirstName} #{@shift.takingLastName} - #{@shift.takingEmail}
              %li  #{@shift.firstName} #{@shift.lastName} - #{@shift.email}

        %td{:width => '40px'}
      %tr
        %td{:colspan => 3}
     

app/views/shifts/show.html.haml
%h3.clear
  #{@shift.firstName} #{@shift.lastName}'s Shift
%ul.span-22
  %li
    Email:
    = @shift.email
  %li
    Shift Type:
    = @shift.shiftType
  %li
    Shift Date:
    = @shift.date.strftime('%a, %B %d, %Y')
  %li
    Shift Hours:
    #{@shift.starttime.strftime('%I:%M %p')} - #{@shift.endtime.strftime('%I:%M %p')}
-if !@shift.takingEmail.nil?
  %h3.clear Taker's Information
  %ul.span-22
    %li
      Name:
      #{@shift.takingFirstName} #{@shift.takingLastName}
    %li
      Email:
      = @shift.takingEmail


%p.span-22.clear
  = link_to 'all shifts', shifts_path, :id => "back"
  - if @shift.takingEmail.nil?
    = link_to 'Take Shift', edit_shift_path(@shift), :class => 'button white'

app/views/splash/index.html.haml
%div.span-22
  %h3.clear Shift Switch Policy
  %p
    This is the Shift Switch, which has been created by the Scheduling Team to facilitate easy shift swaps among employees. The Shift Switch requires you to use your Apple email address.
  %p
    To submit a shift for another employee to take, please click on the Give a Shift button. To view available shifts and to take a shift, use the appropriate buttons to the right of the listed shift.
  %p
    Once a shift is taken, the person who posted the shift, the person taking the shift and NMA Schedule are emailed a notification. If you do not receive an email notification, please resubmit taking the shift, as the request did not fully process.
  %ol
    %h6 As a reminder, there are a few guidelines for switching shifts:
    %li Please double check you are not already working on the day you take a shift.
    %li Employees cannot work more than 8 total hours on a given day, even with split shifts. Also employees cannot work over 40 hours a week (Saturday-Friday).
    %li Shift switches must occur between employees in the same department (ICS/ICS, Red Zone/Red Zone, Genius/Genius etc.)
    %li If you are a Full Time employee giving up a shift, please notify NMA Schedule separately if you would like vacation or sick pay for that day.
    %li Family Room shifts involve an extra level of review to accommodate staffing, so a Family Room switch is not approved until you receive an email specifically approving it.
    %li FRSs may switch with other FRSs or Creatives and vice-versa.  Special attention needs to be paid when switching any shifts that may contain Personal Training sessions due to to trainer knowledge.
    %li Geniuses may only switch with other Geniuses.
    %li No switches with any team members outside of the Family Room.  This means no Specialists are able to take FR shifts. 
    %li The Shift Switch App has now switched #{Shift.count} shifts!!

  %p.span-22
    = link_to 'Give a New Shift', new_shift_path, :class => "button white"